npm-shrinkwrap.json
package.json
src/app/controllers/controller.index.js
src/test/app/specs/controllers/controllers.index.spec.js

Release v2.0.1

---

npm-shrinkwrap.json
package.json
src/public/sass/_zero-target-perf-table.scss

MI 336 black bar on zero targets table

Release v2.1.2

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.hvc-groups.js
src/app/controllers/controller.overseas-regions.js
src/app/controllers/controller.sector-teams.js
src/app/views/partials/hvc-performance-summary.html

Release v2.3.2

---

npm-shrinkwrap.json
package.json
src/app/views/layout.html
src/public/sass/main.scss

Release v2.3.5

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.index.js
src/app/lib/service/service.backend.js
src/app/lib/transformers/os-regions.js
src/app/views/index.html
src/data/create-backend-fake-stubs.js
src/data/faker/backend/scripts/generate-all.js
src/data/faker/backend/scripts/generate-os-regions.js
src/data/faker/backend/scripts/os-regions-json.js
src/data/schema/backend/os_regions/index.schema.json
src/public/sass/_index.scss
src/test/app/fake-data/backend/os_regions/index.json
src/test/app/specs/controllers/controllers.index.spec.js
src/test/app/specs/lib/service/service.backend.spec.js
src/test/app/specs/lib/transformers/os-regions.spec.js

Release v2.4.0

---

npm-shrinkwrap.json
package.json
src/app/lib/service/service.backend.js
src/test/app/specs/lib/service/service.backend.spec.js

Release v2.4.1

---

npm-shrinkwrap.json
package.json
src/app/views/hvc-groups/detail.html

Add zero target table to HVC Group pages

Release v2.7.1

---

npm-shrinkwrap.json
package.json
src/app/lib/transformers/months.js
src/test/app/specs/lib/transformers/months.spec.js

Release v2.7.3

---

npm-shrinkwrap.json
package.json
src/public/sass/_overview-progress.scss

Release v2.8.2

---

npm-shrinkwrap.json
package.json
src/app/lib/middleware/globals.js
src/app/lib/middleware/year.js
src/app/views/hvc/detail.html
src/app/views/layout.html
src/app/views/sector/detail.html
src/public/sass/_monthly-performance.scss
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/middleware/globals.spec.js
src/test/app/specs/lib/middleware/year.spec.js

Release v3.1.1

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/lib/static-globals.js
src/app/views/layout.html
src/app/views/macros/url.html
src/test/app/specs/lib/static-globals.spec.js

Change top feedback link to go to survey

Release v3.3.0

---

npm-shrinkwrap.json
package.json
src/app/lib/app.js
src/app/lib/middleware/force-https.js

Release v3.3.1

---

.circleci/config.yml
.gitignore
npm-shrinkwrap.json
package.json
src/app/views/index.html
src/test/ci/helpers/write-report.js
src/test/ci/setup.sh
src/test/ci/specs/404.spec.js
src/test/ci/specs/index.spec.js
src/test/ci/test-config.js

Add aXe tests and assert for 0 violations
* add test for osRegions flag
* add new accessibility-report directory to capture failure reports

Release v4.1.2

---

npm-shrinkwrap.json
package.json
src/app/lib/transformers/os-regions-overview-groups.js
src/test/app/specs/lib/transformers/os-regions-overview-group.spec.js

Release 4.3.1

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/controllers/controller.saml.js
src/app/lib/render-error.js
src/app/lib/reporter.js
src/app/views/error/default.html
src/app/views/error/not-mi.html
src/app/views/error/unable-to-login.html
src/test/app/specs/controllers/controller.saml.spec.js
src/test/app/specs/lib/render-error.spec.js
src/test/app/specs/lib/reporter.spec.js

Release v4.4.0

---

npm-shrinkwrap.json
package.json
src/app/lib/app.js
src/app/lib/middleware/errors.js
src/app/lib/render-error.js
src/app/views/error/404.html
src/app/views/error/default.html
src/app/views/error/not-mi.html
src/app/views/error/unable-to-login.html
src/public/sass/_error.scss
src/public/sass/main.scss
src/test/app/specs/lib/middleware/errors.spec.js

Release v4.5.0

---

npm-shrinkwrap.json
package.json
src/app/views/layout.html

Release 4.6.0

---

.nycrc
npm-shrinkwrap.json
package.json
src/test/app/fake-data/backend/sector_teams/overview.json
src/test/app/specs/config.spec.js
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/create-signature.spec.js
src/test/app/specs/lib/graphs/get-ceil.spec.js
src/test/app/specs/lib/logger.spec.js
src/test/app/specs/lib/middleware/data.spec.js
src/test/app/specs/lib/middleware/force-https.spec.js
src/test/app/specs/lib/nunjucks-filters/date-only.spec.js
src/test/app/specs/lib/nunjucks-filters/date-with-time.spec.js
src/test/app/specs/lib/service/service.backend.spec.js
src/test/app/specs/lib/transformers/os-regions-overview-group.spec.js
src/test/app/specs/lib/transformers/sector-teams-overview.spec.js
src/test/app/specs/lib/view-models/hvc-target-performance.spec.js
src/test/ci/wait.js

Release v4.7.1

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.saml.js
src/test/app/specs/controllers/controller.saml.spec.js

Release v4.7.2

---

.gitignore
npm-shrinkwrap.json
package.json
src/test/backstop/backstop.json

Release v4.7.3

---

npm-shrinkwrap.json
package.json
src/app/lib/static-globals.js
src/app/views/partials/year-selector.html
src/public/sass/_year-selector.scss
src/test/app/specs/lib/static-globals.spec.js

Release v4.8.0

---

npm-shrinkwrap.json
package.json
src/app/lib/transformers/sector-teams-overview.js
src/data/schema/backend/sector_teams/overview.schema.json
src/test/app/fake-data/backend/sector_teams/overview.json

Release v4.8.1

---

npm-shrinkwrap.json
package.json
src/app/views/layout.html

Username bug - only show username when we have one to display

Release v4.9.1

---

npm-shrinkwrap.json
package.json
src/app/lib/nunjucks-filters/date-with-time.js
src/public/sass/main.scss
src/test/app/specs/lib/nunjucks-filters/date-with-time.spec.js
src/test/backstop/backstop.json

Release v4.10.0

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.index.js
src/app/views/index.html
src/test/app/specs/controllers/controller.index.spec.js
src/test/app/specs/lib/app.spec.js
src/test/ci/specs/index.spec.js

Remove osRegions flag and display list on homepage by default

Release v4.11.0

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.hvc.js
src/app/lib/backend-request.stub.js
src/app/lib/data-sets/sector-pie-charts.js
src/app/lib/data-sets/target-progress.js
src/app/lib/service/service.backend.js
src/app/lib/view-models/hvc-detail.js
src/app/lib/view-models/sector-hvc-summary.js
src/app/routes.js
src/app/views/hvc/detail.html
src/app/views/layout.html
src/data/faker/backend/scripts/generate-hvc.js
src/data/fetch-backend-stubs.js
src/data/schema/backend/hvc/hvc.schema.json
src/public/js/components/component.target-progress.js
src/public/js/mi.js
src/public/js/pages/page.hvc.js
src/public/js/pages/page.sector.js
src/public/sass/page/_hvc.scss
src/test/app/fake-data/backend/hvc/hvc.json
src/test/app/fake-data/backend/hvc/markets.json
src/test/app/specs/controllers/controller.hvc.spec.js
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/backend-request.stub.spec.js
src/test/app/specs/lib/data-sets/target-progress.spec.js
src/test/app/specs/lib/service/service.backend.spec.js
src/test/app/specs/lib/view-models/hvc-detail.spec.js
src/test/app/specs/lib/view-models/sector-hvc-summary.spec.js

Release v4.12.0

---

npm-shrinkwrap.json
package.json
src/app/views/error/not-mi.html

Not in the MI group message bug

Release v4.12.1

---

npm-shrinkwrap.json
package.json
src/app/lib/nunjucks-filters/large-number.js
src/test/app/specs/lib/nunjucks-filters/large-number.spec.js

MI-714 values under 10k show in k not m

Release v4.12.2

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.index.js
src/test/app/helpers/spy.js
src/test/app/specs/controllers/controller.hvc-groups.spec.js
src/test/app/specs/controllers/controller.hvc.spec.js
src/test/app/specs/controllers/controller.index.spec.js
src/test/app/specs/controllers/controller.login.spec.js
src/test/app/specs/controllers/controller.overseas-regions.spec.js
src/test/app/specs/controllers/controller.sector-teams.spec.js

Release v4.12.3

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/lib/service/service.backend.js
src/app/views/layout.html
src/test/app/fake-data/backend/user/me.internal.json
src/test/app/specs/lib/service/service.backend.spec.js

Release v4.13.0

---

npm-shrinkwrap.json
package.json
src/app/routes.js

MI-718 username on hvc detail page

Release v4.13.1

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.index.js
src/app/lib/service/service.backend.js
src/app/routes.js
src/app/views/index.html
src/data/faker/backend/scripts/generate-global-hvcs.js
src/data/schema/backend/global_hvcs/index.schema.json
src/public/sass/page/_index.scss
src/test/app/fake-data/backend/global_hvcs/index.json
src/test/app/specs/controllers/controller.index.spec.js
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/service/service.backend.spec.js

Release v4.14.0

---

npm-shrinkwrap.json
package.json

Release v4.14.1

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.index.js
src/app/lib/service/service.backend.js
src/app/lib/view-models/global-summary.js
src/app/views/index.html
src/data/create-backend-fake-stubs.js
src/data/faker/backend/scripts/generate-global-hvcs.js
src/data/faker/backend/scripts/generate-global-wins.js
src/data/faker/backend/scripts/global-hvcs-json.js
src/data/faker/backend/scripts/global-wins-json.js
src/data/schema/backend/global_wins/index.schema.json
src/public/sass/_layout.scss
src/public/sass/main.scss
src/public/sass/page/_index.scss
src/public/sass/partials/_global-performance.scss
src/test/app/fake-data/backend/global_wins/index.json
src/test/app/specs/controllers/controller.index.spec.js
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/service/service.backend.spec.js
src/test/app/specs/lib/view-models/global-summary.spec.js
src/test/ci/specs/index.spec.js

Add global performance to home page

Release v4.16.0

---

Dockerfile
npm-shrinkwrap.json
package.json

Release v4.16.2

---

npm-shrinkwrap.json
package.json
src/public/sass/_mi-colours.scss
src/public/sass/_win-table.scss
src/test/ci/helpers/accessibility-check.js
src/test/ci/helpers/take-screenshot.js
src/test/ci/specs/404.spec.js
src/test/ci/specs/hvc-group.spec.js
src/test/ci/specs/index.spec.js
src/test/ci/specs/os-region.spec.js
src/test/ci/specs/os-regions-overview.spec.js
src/test/ci/specs/sector-team.spec.js
src/test/ci/specs/sector-teams-overview.spec.js

Release v4.16.3

---

npm-shrinkwrap.json
package.json
src/app/views/hvc-groups/detail.html
src/app/views/hvc/detail.html
src/app/views/sector/detail.html

MI-776 fix: unconfirmed target progress bar not visible

Release 4.16.4

---

npm-shrinkwrap.json
package.json
src/app/lib/app.js
src/app/lib/backend-request.stub.js
src/app/lib/middleware/date-range.js
src/app/lib/middleware/globals.js
src/app/lib/service/service.backend.js
src/app/routes.js
src/app/views/macros/url.html
src/app/views/sector-teams/wins.html
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/backend-request.stub.spec.js
src/test/app/specs/lib/middleware/date-range.spec.js
src/test/app/specs/lib/middleware/globals.spec.js
src/test/app/specs/lib/service/service.backend.spec.js

Add support for date[start] and date[end] in url

Release v5.2.0

---

npm-shrinkwrap.json
package.json
src/app/lib/middleware/headers.js
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/middleware/headers.spec.js

Release v5.3.1

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.date.js
src/app/routes.js
src/app/views/select-dates.html
src/test/app/specs/controllers/controller.date.spec.js

Release v5.4.1

---

npm-shrinkwrap.json
package.json
src/app/views/select-dates.html

Release v5.4.2

---

npm-shrinkwrap.json
package.json
src/public/sass/_win-table.scss

Release v5.6.1

---

npm-shrinkwrap.json
package.json
src/app/views/index.html

Mi 832 gloval hvcs bug

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/lib/transformers/campaigns.js
src/app/routes.js
src/app/views/hvc/wins.html
src/app/views/macros/hvc-target-performance.html
src/app/views/macros/hvc-zero-target-performance.html
src/app/views/macros/win-tables.html
src/app/views/posts/non-hvc-wins.html
src/public/sass/_error.scss
src/public/sass/components/_hvc-target-performance.scss
src/public/sass/components/_zero-target-perf-table.scss
src/test/app/specs/lib/transformers/campaigns.spec.js

MI-841 add number of wins
Some other small tweaks

Release v5.8.0

---

npm-shrinkwrap.json
package.json
src/app/lib/service/service.backend.js
src/app/views/overseas-regions/overview.html
src/public/sass/page/_overseas-regions-overview.scss

Release v5.9.1

---

npm-shrinkwrap.json
package.json
src/app/lib/service/service.backend.js
src/data/fetch-backend-stubs.js
src/data/schema/backend/uk_regions/win_table.schema.json
src/test/app/fake-data/backend/uk_regions/win_table.json
src/test/app/specs/lib/app.spec.js
src/test/app/specs/lib/service/service.backend.spec.js

Release v5.9.2

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.saml.js
src/test/app/specs/controllers/controller.saml.spec.js
src/test/app/specs/lib/app.spec.js

Only send back sessionid cookie from backend

Release v5.10.1

---

npm-shrinkwrap.json
package.json
src/app/views/macros/win-table.html

Update heading as requested by Gino in demo

Table heading

---

npm-shrinkwrap.json
package.json
src/app/lib/data-sets/target-progress.js
src/app/views/hvc-groups/detail.html
src/app/views/hvc/detail.html
src/app/views/index.html
src/app/views/macros/target-progress-bar.html
src/app/views/sector/detail.html
src/public/js/components/component.target-progress.js
src/public/js/pages/page.hvc.js
src/public/js/pages/page.sector.js
src/test/app/specs/lib/data-sets/target-progress.spec.js

Fix big with target progress amount.

Target progress bug

---

npm-shrinkwrap.json
package.json
src/app/views/index.html
src/app/views/layout.html
src/public/sass/_layout.scss
src/public/sass/page/_index.scss
src/public/sass/partials/_global-performance.scss
src/test/ci/specs/index.spec.js

Release v5.12.0

---

npm-shrinkwrap.json
package.json
src/app/lib/middleware/data.js
src/app/lib/middleware/errors.js
src/test/app/specs/controllers/controller.saml.spec.js
src/test/app/specs/lib/middleware/data.spec.js
src/test/app/specs/lib/middleware/errors.spec.js

Release v5.12.1

---

npm-shrinkwrap.json
package.json
src/app/lib/view-models/uk-region-summary.js
src/app/views/uk-regions/detail.html
src/test/app/specs/lib/view-models/uk-region-sumary.spec.js

Release v5.13.0

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.index.js
src/test/app/specs/controllers/controller.index.spec.js
src/test/ci/specs/index.spec.js

Release v5.15.0

---

npm-shrinkwrap.json
package.json
src/app/lib/backend-request.stub.js
src/app/lib/service/service.backend/investment.js
src/app/lib/transformers/fdi/overview-yoy.js
src/app/lib/transformers/fdi/overview.js
src/app/sub-apps/investment/views/index.html
src/app/views/macros/dates.html
src/data/create-backend-fake-stubs.js
src/data/faker/backend/scripts/generate-all.js
src/data/faker/backend/scripts/investment/generate-fdi.js
src/data/faker/backend/scripts/lib/generate-schema.js
src/data/faker/backend/scripts/lib/json-creators/investment/fdi-json.js
src/data/fetch-backend-stubs.js
src/data/schema/backend/investment/fdi/overview-yoy.schema.json
src/data/schema/backend/investment/fdi/overview.schema.json
src/public/sass/_mi-typeography.scss
src/public/sass/investment.scss
src/public/sass/page/investment/_overview.scss
src/test/app/fake-data/backend/investment/fdi/overview-yoy.json
src/test/app/fake-data/backend/investment/fdi/overview.json
src/test/app/fake-data/backend/investment/fdi/overview_no-performance.json
src/test/app/specs/app.spec.js
src/test/app/specs/lib/backend-request.stub.spec.js
src/test/app/specs/lib/service/service.backend/investment.spec.js
src/test/app/specs/lib/transformers/fdi/overview-yoy.spec.js
src/test/app/specs/lib/transformers/fdi/overview.spec.js

Release v6.1.0

---

npm-shrinkwrap.json
package.json
src/public/sass/main.scss
src/public/sass/print.scss

Release v6.1.1

---

npm-shrinkwrap.json
package.json
src/app/lib/transformers/fdi/overview-yoy.js
src/app/routes/index.js
src/app/sub-apps/investment/views/index.html
src/app/views/layout.html
src/test/app/fake-data/backend/investment/fdi/overview-yoy.json
src/test/app/specs/lib/transformers/fdi/overview-yoy.spec.js

Remove FDI feature flag
Hide FDI sector teams

Release v6.3.0

---

.nycrc
npm-shrinkwrap.json
package.json
src/app/config.js
src/app/controllers/controller.login.js
src/app/controllers/controller.saml.js
src/app/lib/get-session-id.js
src/app/lib/render-error.js
src/app/lib/service/service.backend/_helpers.js
src/app/lib/service/service.backend/index.js
src/app/middleware/user.js
src/app/routes/index.js
src/test/app/specs/app.spec.js
src/test/app/specs/controllers/controller.login.spec.js
src/test/app/specs/lib/get-session-id.spec.js
src/test/app/specs/lib/render-error.spec.js
src/test/app/specs/lib/service/service.backend/_helpers.spec.js
src/test/app/specs/lib/service/service.backend/index.spec.js
src/test/app/specs/middleware/user.spec.js

Release v6.5.0

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/controllers/controller.login.js
src/test/app/specs/controllers/controller.login.spec.js

Clear user cookie to show correct name depending on login provider

Release v6.5.1

---

.codeclimate.yml
npm-shrinkwrap.json
package.json
src/app/middleware/errors.js

Release v6.5.2

---

npm-shrinkwrap.json
package.json
src/public/sass/print.scss

MI 1039 add "Internal use only" to printed pages

Release v6.5.3

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.download.js
src/app/controllers/controller.index.js
src/app/lib/service/service.backend/index.js
src/app/lib/urls.js
src/app/routes/index.js
src/app/views/index.html
src/public/sass/page/_index.scss
src/test/app/specs/app.spec.js
src/test/app/specs/controllers/controller.download.spec.js
src/test/app/specs/controllers/controller.index.spec.js
src/test/app/specs/controllers/controller.login.spec.js
src/test/app/specs/lib/service/service.backend/index.spec.js
src/test/app/specs/lib/urls.spec.js

Add download data link to export homepage

Release v6.8.0

---

.circleci/config.yml
.dockerignore
Dockerfile
npm-shrinkwrap.json
package.json

Release v6.9.0

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.login.js
src/test/app/specs/controllers/controller.login.spec.js

Release v6.9.1

---

npm-shrinkwrap.json
package.json
src/app/routes/index.js
src/test/app/specs/app.spec.js

Release v6.10.1

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/controllers/controller.download.js
src/app/lib/service/service.backend/index.js
src/app/views/downloads/list.html
src/test/app/specs/app.spec.js
src/test/app/specs/controllers/controller.download.spec.js
src/test/app/specs/lib/service/service.backend/index.spec.js

Release v6.11.0

---

npm-shrinkwrap.json
package.json
src/app/views/downloads/list.html
src/data/schema/backend/csv/list.schema.json
src/public/sass/page/_downloads.scss

MI 1106 download csv by sector

Release v6.12.0

---

npm-shrinkwrap.json
package.json
src/app/views/layout.html
src/public/sass/_layout.scss

Add some JS to hide experiments

Hide experiments

---

npm-shrinkwrap.json
package.json
src/app/lib/service/service.backend/investment/fdi.js
src/app/lib/urls.js
src/app/sub-apps/investment/controllers/controller.uk-regions.js
src/app/sub-apps/investment/routes.js
src/app/sub-apps/investment/views/index.html
src/app/sub-apps/investment/views/macros/tabs/fdi/uk-regions.html
src/app/sub-apps/investment/views/uk-regions/detail.html
src/app/sub-apps/investment/views/uk-regions/hvc-performance.html
src/app/sub-apps/investment/views/uk-regions/non-hvc-performance.html
src/app/sub-apps/investment/views/uk-regions/non-hvc-wins.html
src/app/sub-apps/investment/views/uk-regions/overview.html
src/app/sub-apps/investment/views/uk-regions/wins.html
src/data/schema/backend/investment/fdi/uk_regions/index.schema.json
src/test/app/fake-data/backend/investment/fdi/uk_regions/index.json
src/test/app/specs/app.spec.js
src/test/app/specs/lib/service/service.backend/investment/fdi.spec.js
src/test/app/specs/lib/urls.spec.js
src/test/app/specs/sub-apps/investment/controllers/controller.uk-regions.spec.js

Add placeholders for all fdi uk region pages

Release v6.14.0

---

npm-shrinkwrap.json
package.json
src/app/lib/transformers/csv-files.js
src/app/views/downloads/list.html
src/data/schema/backend/csv/list.schema.json
src/test/app/fake-data/backend/csv/all_files.companies.json
src/test/app/fake-data/backend/csv/all_files.companies.regions.json
src/test/app/fake-data/backend/csv/all_files.companies.sectors.json
src/test/app/fake-data/backend/csv/all_files.contacts.json
src/test/app/fake-data/backend/csv/all_files.contacts.regions.json
src/test/app/fake-data/backend/csv/all_files.contacts.sectors.json
src/test/app/fake-data/backend/csv/all_files.json

MI 1129 change csv download dates

Release v6.15.0

---

npm-shrinkwrap.json
package.json
src/app/views/downloads/list.html
src/data/schema/backend/csv/list.schema.json

Add start date for SDI monthly download dates

Release v6.15.1

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/controllers/controller.login.js
src/app/lib/save-user.js
src/app/middleware/user.js
src/test/app/specs/controllers/controller.login.spec.js
src/test/app/specs/lib/save-user.spec.js
src/test/app/specs/middleware/user.spec.js

Set user cookie to expire after a certain time

Release v6.16.0

---

npm-shrinkwrap.json
package.json
src/app/config.js

Ensure cookie maxAge is a number

Release v6.16.1

---

Gruntfile.js
npm-shrinkwrap.json
package.json
src/app/views/base.html
src/public/js/layout.js

Release v6.17.1

---

npm-shrinkwrap.json
package.json
src/app/views/index.html
src/app/views/layout.html
src/public/sass/page/_index.scss

Release v6.17.2

---

npm-shrinkwrap.json
package.json
src/app/views/macros/top-markets.html
src/app/views/macros/win-table.html
src/public/sass/components/_win-table.scss

Release v6.17.3

---

npm-shrinkwrap.json
package.json
src/app/lib/service/service.backend/investment/fdi.js
src/app/sub-apps/investment/controllers/controller.sector-teams.js
src/app/sub-apps/investment/view-models/fdi-sector-team-markets.js
src/app/sub-apps/investment/views/index.html
src/app/sub-apps/investment/views/macros/sector-team-markets.html
src/app/sub-apps/investment/views/sector-teams/overview.html
src/data/create-backend-fake-stubs.js
src/data/faker/backend/scripts/investment/fdi/generate-sector-teams.js
src/data/faker/backend/scripts/lib/json-creators/investment/fdi/sector-teams-json.js
src/data/schema/backend/investment/fdi/sector_teams/overview.schema.json
src/public/sass/investment.scss
src/public/sass/page/investment/_sector-team.scss
src/public/sass/page/investment/_sector-teams-overview.scss
src/test/app/fake-data/backend/investment/fdi/sector_teams/overview.json
src/test/app/specs/app.spec.js
src/test/app/specs/lib/service/service.backend/investment/fdi.spec.js
src/test/app/specs/sub-apps/investment/controllers/controller.sector-teams.spec.js
src/test/app/specs/sub-apps/investment/view-models/fdi-sector-team-markets.spec.js

Release v6.19.0

---

npm-shrinkwrap.json
package.json
src/app/sub-apps/investment/view-models/fdi-sector-team-markets.js
src/data/schema/backend/investment/fdi/sector_teams/overview.schema.json
src/test/app/fake-data/backend/investment/fdi/sector_teams/overview.json
src/test/app/specs/sub-apps/investment/view-models/fdi-sector-team-markets.spec.js

Use description when available for FDI sector teams overview name

Release v6.19.1

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.refresh.js
src/app/views/me.html
src/test/app/specs/app.spec.js
src/test/app/specs/controllers/controller.refresh.spec.js

MI 1152 show user when using refresh

Release v6.19.2

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.login.js
src/app/lib/urls.js
src/app/routes/index.js
src/app/views/base.html
src/app/views/me.html
src/test/app/specs/app.spec.js
src/test/app/specs/controllers/controller.login.spec.js
src/test/app/specs/lib/urls.spec.js

Release v6.20.0

---

npm-shrinkwrap.json
package.json
src/app/lib/graphs/closest-greatest-integer.js
src/app/lib/graphs/create-scale.js
src/test/app/specs/lib/graphs/closest-greatest-integer.spec.js
src/test/app/specs/lib/graphs/create-scale.spec.js

MI-991 fix scale on monthly graph

Release v6.20.1

---

npm-shrinkwrap.json
package.json

Release v6.21.1

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.download.js
src/app/lib/service/analytics.js
src/app/lib/transformers/csv-files.js
src/app/lib/urls.js
src/app/views/downloads/list.html
src/test/app/fake-data/backend/csv/all_files.json
src/test/app/specs/controllers/controller.download.spec.js
src/test/app/specs/lib/service/analytics.spec.js
src/test/app/specs/lib/transformers/csv-files.spec.js
src/test/app/specs/lib/urls.spec.js

Release v6.23.0

---

npm-shrinkwrap.json
package.json
src/app/views/downloads/list.html
src/public/sass/page/_downloads.scss

Release v6.23.1

---

npm-shrinkwrap.json
package.json
src/app/routes/index.js
src/app/sub-apps/investment/routes.js

Fix investment urls not getting redirected after login

Release v6.23.2

---

npm-shrinkwrap.json
package.json
src/app/lib/static-globals.js
src/test/app/specs/lib/static-globals.spec.js

Release v6.23.3

---

app.json
npm-shrinkwrap.json
package.json

Release v6.23.4

---

npm-shrinkwrap.json
package.json
src/test/backstop/backstop.js

Update deps, fix backstop script

Release v6.24.1

---

npm-shrinkwrap.json
package.json
src/test/backstop/backstop.js

Add backstop tests to cover all investment pages

Release v6.24.2

---

npm-shrinkwrap.json
package.json
src/app/controllers/controller.countries.js
src/app/controllers/controller.overseas-regions.js
src/app/controllers/controller.posts.js
src/app/controllers/controller.sector-teams.js
src/app/controllers/controller.uk-regions.js
src/app/lib/service/analytics.js
src/app/lib/static-globals.js
src/app/lib/transformers/export/win-list.js
src/app/views/hvc/wins.html
src/app/views/macros/table-standard-types.html
src/app/views/sector/detail.html
src/app/views/uk-regions/detail.html
src/app/views/uk-regions/non-hvc-wins.html
src/app/views/uk-regions/wins.html
src/public/sass/components/_table-standard.scss
src/public/sass/components/_win-table.scss
src/test/app/specs/controllers/controller.countries.spec.js
src/test/app/specs/controllers/controller.overseas-regions.spec.js
src/test/app/specs/controllers/controller.posts.spec.js
src/test/app/specs/controllers/controller.sector-teams.spec.js
src/test/app/specs/controllers/controller.uk-regions.spec.js
src/test/app/specs/lib/service/analytics.spec.js
src/test/app/specs/lib/static-globals.spec.js
src/test/app/specs/lib/transformers/export/win-list.spec.js

MI 1209 part 2
Custom columns on win tables for UK Regions
Enable "Load all" for Top Markets

Release v7.1.0

---

npm-shrinkwrap.json
package.json
src/app/views/downloads/list.html
src/data/schema/backend/csv/list.schema.json

Release v7.2.0

---

npm-shrinkwrap.json
package.json
src/app/lib/urls.js
src/app/views/downloads/list.html
src/test/app/specs/lib/urls.spec.js

Release v7.2.1

---

npm-shrinkwrap.json
package.json
src/app/lib/service/analytics.js
src/test/app/specs/lib/service/analytics.spec.js

MI-1246 report to Sentry when no GA id found

Release v7.2.2

---

npm-shrinkwrap.json
package.json
src/app/lib/service/analytics.js
src/test/app/specs/lib/service/analytics.spec.js

MI-1255 stop tracking internal users

Release v7.3.1

---

.codeclimate.yml
npm-shrinkwrap.json
package.json
src/app/views/downloads/list.html

MI-1253 Downloads heading change, update codeclimate config

Release v7.3.2

---

.circleci/config.yml
npm-shrinkwrap.json
package.json
src/app/config.js
src/app/controllers/controller.download.js
src/app/views/downloads/list.html
src/public/sass/page/_downloads.scss
src/test/app/specs/controllers/controller.download.spec.js

Release v7.6.0

---

npm-shrinkwrap.json
package.json

Release v7.6.2

---

npm-shrinkwrap.json
package.json
src/app/lib/view-models/hvc-target-performance.js
src/app/views/hvc-groups/detail.html
src/app/views/sector/detail.html
src/test/app/specs/lib/view-models/hvc-target-performance.spec.js

MI-1444 fix incorrect financial year in title bug

Release v7.6.3

---

npm-shrinkwrap.json
package.json
src/app/lib/financial-year.js
src/test/app/specs/lib/financial-year.spec.js

Fix date selector bug where months were missing when current month is March

Release v7.7.1

---

npm-shrinkwrap.json
package.json

Release v7.7.2

---

npm-shrinkwrap.json
package.json
src/app/sub-apps/investment/views/index.html

Update FDI figures to be more precise
Fix typo

Release v7.7.3

---

npm-shrinkwrap.json
package.json
src/app/sub-apps/investment/lib/sort-region-progress.js
src/test/app/specs/sub-apps/investment/lib/sort-region-progress.spec.js

Fix sorting of safeguarded jobs for UK regions

Release v7.8.1

---

npm-shrinkwrap.json
package.json
src/app/lib/safe-path.js
src/test/app/specs/lib/safe-path.spec.js

MI-1472 A path is sometimes not passed to the safe-path function
Make it handle different types of input without erroring

Release v7.8.2

---

npm-shrinkwrap.json
package.json
src/app/lib/render-error.js
src/test/app/specs/lib/render-error.spec.js

MI-1473 fix expired session return path

Release v7.8.3

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/lib/render-error.js
src/app/lib/urls.js
src/app/views/error/404.html
src/app/views/error/default.html
src/app/views/error/not-mi.html
src/app/views/error/unable-to-login.html
src/test/app/fake-data/backend/sector_teams/not_found.json
src/test/app/specs/app.spec.js
src/test/app/specs/lib/render-error.spec.js
src/test/app/specs/lib/urls.spec.js

MI-1474 Fix sentry error around login
Update error page content and handle 404 from backend

Release v7.8.4

---

npm-shrinkwrap.json
package.json
src/app/sub-apps/investment/lib/sort-region-progress.js
src/app/sub-apps/investment/view-models/fdi-performance-region-progress.js
src/app/sub-apps/investment/views/index.html
src/app/sub-apps/investment/views/macros/table-region-progress.html
src/test/app/specs/sub-apps/investment/controllers/controller.index.spec.js
src/test/app/specs/sub-apps/investment/lib/sort-region-progress.spec.js
src/test/app/specs/sub-apps/investment/view-models/fdi-performance-region-progress.spec.js

Release v7.9.1

---

npm-shrinkwrap.json
package.json
src/app/sub-apps/investment/controllers/controller.index.js
src/app/sub-apps/investment/views/index.html
src/test/app/specs/app.spec.js
src/test/app/specs/sub-apps/investment/controllers/controller.index.spec.js
src/test/ci/specs/investment/index.spec.js

Release v7.10.0

---

npm-shrinkwrap.json
package.json
src/app/config.js
src/app/lib/static-globals.js
src/app/middleware/year.js
src/app/views/downloads/list.html
src/test/app/specs/lib/static-globals.spec.js
src/test/app/specs/middleware/globals.spec.js

Release v7.10.1

---

src/app/sub-apps/investment/views/index.html

Update content around opening the dashboard in data studio

---

package-lock.json
package.json

Updated the FDI dashboard page as we now have a link to Google data studio that all users can access.

Release v7.10.9

---

src/app/sub-apps/investment/views/index.html

Add overseas region links to Google data studio.

Update content for overseas regions.

---

package.json

This updates the content of overseas region links that go to Google data studio

Update version to 7.10.11

---

package-lock.json
package.json
src/app/sub-apps/investment/views/index.html

Adds new sector cluster links to FDI dashboard page

Feature sectors cluster links

---

package-lock.json
package.json
src/app/sub-apps/investment/views/index.html

Updating the content around the FDI dashboard data studio links.

Update content on FDI dashboard

---

src/app/config.js
src/test/app/specs/lib/transformers/permitted-apps.spec.js

Updating paths into Investments.

Changing /investment-projects to /investments

---

package-lock.json
package.json

Updated package.json for new release

Release 7.11.0

---

src/app/sub-apps/investment/views/annual-report-lists/2018-2019.html
src/app/sub-apps/investment/views/annual-report-lists/2019-2020.html
src/app/sub-apps/investment/views/index.html
src/public/sass/page/_index.scss
src/test/app/specs/app.spec.js

Added 2019/2020 FDI report links

Added 2019/2020 FDI report links

---

src/app/sub-apps/investment/views/annual-report-lists/2019-2020.html

Wrong Data Studio links are being used.
Correct the links.

Update wrong links going to Data Studio

---

package-lock.json
package.json

To ensure Market Access get added

Update header component to the latest version

---

.circleci/config.yml
package-lock.json
package.json
src/app/config.js
src/app/controllers/controller.download.js
src/app/views/downloads/list.html
src/public/sass/page/_downloads.scss
src/test/app/specs/controllers/controller.download.spec.js

Remove contacts and companies downloads and replace with links to Data Workspace

Release v7.14.0

---

.circleci/config.yml
package-lock.json
package.json
src/app/config.js
src/app/controllers/controller.download.js
src/app/views/downloads/list.html
src/public/sass/page/_downloads.scss
src/test/app/specs/controllers/controller.download.spec.js

Update banner to include a link to the help article
Add help and fdi links to config, pass to template

Remove all downloads and replace with workspace

---

package-lock.json
package.json

Update backstop and fix some vulnerabilities

Release v8.1.1

---

package-lock.json
package.json
src/app/sub-apps/investment/controllers/controller.index.js
src/app/sub-apps/investment/views/index.html
src/app/views/downloads/list.html
src/public/sass/components/_banners.scss
src/public/sass/main.scss
src/public/sass/page/_downloads.scss
src/test/app/specs/sub-apps/investment/controllers/controller.index.spec.js

Redirects user to Data Workspace.
Moves banner styling to generic update-banner scss file.

Add new banner with link to Data workspace

---

src/app/middleware/headers.js
src/test/app/specs/app.spec.js
src/test/app/specs/middleware/headers.spec.js

According to pen test report we were advised to add this changes:
- Cache-Control headers
- HSTS headers

Updated response headers

---

package-lock.json
package.json

Something went wrong when I made the release tag this morning (it created two tags with no changes associated). This is a fix for that.

Release v8.4.0

---

.circleci/config.yml

Docker repo `grokzen/redis-cluster` removed version `3.x`.

Changed redis-cluster image

---

package-lock.json
package.json

Bump async verison to 2.6.4
